### ISSUE TITLE
RDFMapper tesztjeiben néhol generikus kivételdobás jelzés van specifikusabb helyett

### ISSUE THREAD

**Issue by lyaflora** [BME-MIT-IET/extra2-iet-2020#21]
Az RDFMapper néhány tesztjében generikus kivétel dobását jelezzük a függvény fejlécében. Tudjuk, hogy ezek egy specifikus kivételt fognak dobni, így azokkal kellene helyettesíteni - Exception helyett az adott függvény fejléce felett levő annotációban található expected paraméter típussal.

A következő tesztejben kellene módosítás a következő exceptionökre:
- testUnidentifiable (83. sor) : UnidentifiableObjectException
- testIdentifiableNoIdNoFallback (432. sor) : UnidentifiableObjectException
- testCustomDatatypingOfLiteralWithInvalidDatatypeFatal (467. sor) : RDFMappingException
- testNoInvalidNamespaceToBuilder (539. sor) : IllegalArgumentException
- testNoInvalidPrefixToBuilder (544. sor) : IllegalArgumentException
- testAnnotationsWithInvalidURIFatal (549. sor) : RDFMappingException
- testWriteEnumInvalidIriFatal (638. sor) : RDFMappingException
- testMultipleSubjectsNoIdProvided (715. sor) : RDFMappingException

**Comment by eni020** [comment]
A többi teszt esetében is lehetne specifikálni a dobható kivételeket, például a ModelIO.read() több tesztben is előfordul és IOException-t dobé
